version: 0.2

env:
  parameter-store:
    CODESIGN_PROFILE_ARN: '/iot/rebelthings/codesign/esp32/codesign-profile-arn'
    OTA_BUCKET_PARAMETER_URI: '/iot/rebelthings/hottopsidecar/ota-bucket'
phases:
  install:
    commands:
      - ls -tral
      - echo "Codesign profile ARN $CODESIGN_PROFILE_ARN"
      - echo "OTA Bucket $OTA_BUCKET_PARAMETER_URI"
      - echo "CODEBUILD_SOURCE_REPO_URL $CODEBUILD_SOURCE_REPO_URL"
      - echo "CODEBUILD_SOURCE_VERSION $CODEBUILD_SOURCE_VERSION"
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
