version: 0.2

env:
  parameter-store:
    CODESIGN_PROFILE_ARN: '/iot/rebelthings/codesign/esp32/codesign-profile-arn'
    OTA_BUCKET_PARAMETER_URI: '/iot/rebelthings/hottopsidecar/ota-bucket'
phases:
  install:
    commands:
      - echo Entered the install phase...
      - echo Codesign profile ARN: $CODESIGN_PROFILE_ARN
      - echo OTA bucket parameter URI: $OTA_BUCKET_PARAMETER_URI
  pre_build:
    commands:
      - echo Entered the pre_build phase...
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
