version: 0.2

env:
  parameter-store:
    CODESIGN_PROFILE_ARN: '/iot/rebelthings/codesign/esp32/codesign-profile-arn'
    OTA_BUCKET_PARAMETER_URI: '/iot/rebelthings/hottopsidecar/ota-bucket'
phases:
  build:
    commands:
      - ./deploy/bin/sign-firmware.sh $CODEBUILD_SRC_DIR/deploy $OTA_BUCKET_PARAMETER_URI release $CODESIGN_PROFILE_ARN
  post_build:
    commands:
      - echo Entered the post_build phase...
cache:
  paths:
    - '/root/.m2/**/*'
    - '/root/.npm/**/*'
