on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      aws_account_id:
        required: true
        type: string
      stage:
        required: true
        type: string
jobs:
  build:
    name: Build firmware
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      AWS_REGION: ap-southeast-2
      AWS_ACCOUNT_ID: ${{ inputs.aws_account_id }}
      STAGE: ${{ inputs.stage }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: 'recursive'
      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.1.1
          target: esp32s3
          path: '.'
          command: make build
      - uses: actions/upload-artifact@v4
        with:
          name: firmware.zip
          path: build/firmware.zip
  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: write
    env:
      AWS_REGION: ap-southeast-2
      AWS_ACCOUNT_ID: ${{ inputs.aws_account_id }}
      STAGE: ${{ inputs.stage }}
    steps:
      - uses: actions/download-artifact@master
        with:
          name: firmware.zip
          path: firmware.zip
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: Sync files to S3 bucket
        run: |
          aws s3 cp firmware.zip s3://${{ secrets.AWS_OTA_BUCKET_NAME }}/newBuilds/firmware.zip