name: Environment Deployment
on:
  push:
    branches:
      - main

jobs:
  development:
    uses: ./.github/workflows/deploy_base.yaml
    with:
      environment: dev
      aws_account_id: 407440998404
      stage: dev

